name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up nodejs
        uses: actions/setup-node@v1.2.0
        with:
          node-version: '12.x'

      - name: Set up protoc
        uses: arduino/setup-protoc@v1

      - name: Build all
        run: |
          ./.ci/all-ci build $(git describe)

      - name: Deploy all
        run: |
          ./.ci/all-ci deploy
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          NPM_AUTH_TOKEN: ${{ secrets.BINTRAY_API_KEY }}
